# Generated by Django 5.2.6 on 2025-10-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_features_product_warranty_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="warranty_date",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
